//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Print_PDF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public int EmpNo { get; set; }
        public string EmpName { get; set; }
        public int Salary { get; set; }
        public string DeptName { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> HRA { get; set; }
        public Nullable<decimal> TA { get; set; }
        public Nullable<decimal> DA { get; set; }
        public Nullable<decimal> GrossSalary { get; set; }
        public Nullable<decimal> TDS { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
    }
}
